package at.triply.wcapi.model

data class Order(val discountTotal: String,
                 val orderKey: String,
                 val pricesIncludeTax: Boolean,
                 val _links: OrderLinks,
                 val customerNote: String,
                 val lineItems: List<LineItem>,
                 val couponLines: List<CouponLine>,
                 val billing: BillingInformation,
                 val refunds: List<Refund>,
                 val number: String,
                 val total: String,
                 val shipping: ShippingInformation,
                 val taxLines: List<TaxLine>,
                 val customerUserAgent: String,
                 val paymentMethodTitle: String,
                 val metaData: List<MetaData>,
                 val currency: String,
                 val id: Int,
                 val paymentMethod: String,
                 val shippingTax: String,
                 val transactionId: String,
                 val dateModifiedGmt: String,
                 val cartHash: String,
                 val shippingTotal: String,
                 val cartTax: String,
                 val createdVia: String,
                 val dateCreated: String,
                 val dateCreatedGmt: String,
                 val discountTax: String,
                 val totalTax: String,
                 val version: String,
                 val customerIpAddress: String,
                 val shippingLines: List<String>,
                 val dateModified: String,
                 val parentId: Int,
                 val feeLines: List<FeeLine>,
                 val customerId: Int,
                 val status: String) : Entity

