package at.triply.wcapi.model

class Order(val discount_total: String,
            val order_key: String,
            val prices_include_tax: Boolean,
            //val links: Links,
            val customer_note: String,
            val line_items: List<LineItem>,
            val coupon_lines: List<String>,
            val billing: BillingInformation,
            val refunds: List<Refund>,
            val number: String,
            val total: String,
            val shipping: ShippingInformation,
            val tax_lines: List<TaxLine>,
            val customer_user_agent: String,
            val payment_method_title: String,
            val meta_data: List<MetaData>,
            val currency: String,
            val id: Int,
            val payment_method: String,
            val shipping_tax: String,
            val transaction_id: String,
            val date_modified_gmt: String,
            val cart_hash: String,
            val shipping_total: String,
            val cart_tax: String,
            val created_via: String,
            val date_created: String,
            val date_created_gmt: String,
            val discount_tax: String,
            val total_tax: String,
            val version: String,
            val customer_ip_address: String,
            val shipping_lines: List<String>,
            val date_modified: String,
            val parent_id: Int,
            val fee_lines: List<FeeLine>,
            val customer_id: Int,
            val status: String) : Entity

